juan_luis_lab_homepage:
    path:     /
    defaults: { _controller: JuanLuisLabBundle:Default:index }

juan_luis_lab_task_list:
    path:     /list
    defaults: { _controller: JuanLuisLabBundle:Task:list }

juan_luis_lab_task_new:
    path:     /new
    defaults: { _controller: JuanLuisLabBundle:Task:new }
    methods: [GET|POST]

juan_luis_lab_task_remove:
    path:     /remove/{id}
    defaults: { _controller: JuanLuisLabBundle:Task:remove }

juan_luis_lab_task_update:
    path:     /update/{id}
    defaults: { _controller: JuanLuisLabBundle:Task:update }
    methods: [GET|POST]

juan_luis_lab_task_show:
    path:     /show/{id}
    defaults: { _controller: JuanLuisLabBundle:Task:show }